1$ sh ./grapheme-widths.sh
12345678|2345678|2345678|2345678
{🇳🇴🇨b}  |  ÷ [0.2] REGIONAL INDICATOR SYMBOL LETTER N (RI) × [12.0] REGIONAL INDICATOR SYMBOL LETTER O (RI) ÷ [999.0] REGIONAL INDICATOR SYMBOL LETTER C (RI) ÷ [999.0] LATIN SMALL LETTER B (Other) ÷ [0.3]
{🇳🇴🇨b}78|2345678
{🇳🇴}5678|2345678
{👶🏿👶}  |  ÷ [0.2] BABY (ExtPict) × [9.0] EMOJI MODIFIER FITZPATRICK TYPE-6 (Extend) ÷ [999.0] BABY (ExtPict) ÷ [0.3]
{👶👶🏿X}8|2345678
{á}     |  letter a × acute accent
{á}ooooo|ooooooo
{각}    | Hangul syllables (correct on Firefox)
{각}5678| Hangul syllables (correct on Firefox)
{👩‍👩‍👧‍👦}    | WOMAN+ZWJ+WOMAN+ZWJ+GIRL+ZWJ+BOY
{👩‍👩‍👦}    | WOMAN+ZWJ+WOMAN+ZWJ+BOY
{🤦🏼‍♂️}    |
{🤦🏼‍♂️}5678|2345678
{👩}    | WOMAN
{x哀公}8|23456781234
{哀公xy問}345678|234
2$ 
