1$ sh ./grapheme-widths.sh --tests
12345678|2345678|2345678|2345678
{🇳🇴}    |REGIONAL INDICATOR SYMBOL LETTER N × RI O
{🇳🇴}5678|REGIONAL INDICATOR SYMBOL LETTER N × RI O
{🇩🇪🇳🇴🇫} |REGIONAL INDICATOR SYMBOL LETTER D E N O F
{🇩🇪🇳🇴🇫}8|REGIONAL INDICATOR SYMBOL LETTER D E N O F
{👶🏿👶}  |baby × emoji modifier fitzpatrick type-6 ÷ baby
{👶🏿👶}78|baby × emoji modifier fitzpatrick type-6 ÷ baby
{👶👶🏿X} |
{👶👶🏿X}8|23456781234
{á}     |letter a × acute accent
{á}45678|letter a × acute accent
{각}    |Hangul Jamo
{각}5678|Hangul Jamo
{각=가=각=}     |more Jamo
{각=가=각=}45678|more Jamo
{가=횅=}        |Hangul syllables (pre-composed)
{가=횅=}12345678|Hangul syllables (pre-composed)
{🙋🙋‍♂️}  |person/man raising hand
{🙋🙋‍♂️}78|person/man raising hand
{=🏋=🏋️=🏋🏾‍♀=}     |person lifting weights (plain, emoji); woman lighting weights, medium dark
{=🏋=🏋️=🏋🏾‍♀=}45678|person lifting weights (plain, emoji); woman lighting weights, medium dark
{👩‍👩‍👦}    |woman+zwj+woman+zwj+boy
{👩‍👩‍👦}5678|woman+zwj+woman+zwj+boy
{🤦🏼‍♂️}    |face palm × fitzpatrick type-3 × zwj × male × emoji presentation
{🤦🏼‍♂️}5678|face palm × fitzpatrick type-3 × zwj × male × emoji presentation
{=👩👩‍🎓=👨🏿‍🎓=}     |woman; woman student; man student dark
{=👩👩‍🎓=👨🏿‍🎓=}45678|woman; woman student; man student dark
{x哀公} |
{x哀公}8|23456781234
{/哀︎公︎/}        |Kanji with text presentation
{/哀︎公︎/}12345678|Kanji with text presentation
{哀公xy問}      |
{哀公xy問}345678|234
{⚰⚰}    |coffin coffin
{⚰⚰}5678|coffin coffin
{⚰︎}     |coffin text_presentation
{⚰︎}45678|coffin text_presentation
{⚰️}    |coffin emoji_presentation
{⚰️}5678|coffin emoji_presentation
{É️g️a️l️i️️t️é️}        |Égalité (using separate acute) emoij_presentation
{É️g️a️l️i️️t️é️}1234    |Égalité (using separate acute) emoij_presentation
{🇳🇴🇨b}  |regional indicator symbol letter N (RI) × RI O ÷ RI C ÷ latin small letter b)
{🇳🇴🇨b}78|regional indicator symbol letter N (RI) × RI O ÷ RI C ÷ latin small letter b)
{👩‍👩‍👧‍👦}    |woman+zwj+woman+zwj+girl+zwj+boy
{👩‍👩‍👧‍👦}5678|woman+zwj+woman+zwj+girl+zwj+boy
2$ 
