1$ sh ./grapheme-widths.sh --tests
12345678|2345678|2345678|2345678
{🇳🇴}    |REGIONAL INDICATOR SYMBOL LETTER N × RI O
{🇳🇴}5678|REGIONAL INDICATOR SYMBOL LETTER N × RI O
{🇩🇪🇳🇴🇫} |REGIONAL INDICATOR SYMBOL LETTER D E N O F
{🇩🇪🇳🇴🇫}8|REGIONAL INDICATOR SYMBOL LETTER D E N O F
{👶🏿👶}  |baby × emoji modifier fitzpatrick type-6 ÷ baby
{👶🏿👶}78|baby × emoji modifier fitzpatrick type-6 ÷ baby
{👶👶🏿X} |
{👶👶🏿X}8|23456781234
{á}     |letter a × acute accent
{á}45678|letter a × acute accent
{각}    |Hangul syllables (correct on Firefox)
{각}5678|Hangul syllables (correct on Firefox)
{👩‍👩‍👦}    |woman+zwj+woman+zwj+boy
{👩‍👩‍👦}5678|woman+zwj+woman+zwj+boy
{🤦🏼‍♂️}    |face palm × fitzpatrick type-3 × zwj × male × emoji presentation
{🤦🏼‍♂️}5678|face palm × fitzpatrick type-3 × zwj × male × emoji presentation
{👩}    |woman
{👩}5678|woman781234
{x哀公} |
{x哀公}8|23456781234
{哀公xy問}      |
{哀公xy問}345678|234
{⚰⚰}    |coffin coffin
{⚰⚰}5678|coffin coffin
{⚰︎}     |coffin text_presentation
{⚰︎}45678|coffin text_presentation
{⚰️}    |coffin emoji_presentation
{⚰️}5678|coffin emoji_presentation
{É️g️a️l️i️️t️é️}        |Égalité (using separate acute) emoij_presentation
{É️g️a️l️i️️t️é️}1234    |Égalité (using separate acute) emoij_presentation
{🇳🇴🇨b}  |regional indicator symbol letter N (RI) × RI O ÷ RI C ÷ latin small letter b)
{🇳🇴🇨b}78|regional indicator symbol letter N (RI) × RI O ÷ RI C ÷ latin small letter b)
{👩‍👩‍👧‍👦}    |woman+zwj+woman+zwj+girl+zwj+boy
{👩‍👩‍👧‍👦}5678|woman+zwj+woman+zwj+girl+zwj+boy
2$ 
