[44m[K[33mThis test inserts after every second line in a list, marking cursor with '*'.[m
[44m[K[33mThe foreground and background should be yellow(orange) and blue, respectively.[m
[44m[K[33mPush <RETURN>[m
[44m[K[m
[44m[K[33m   row   5: this is some text[m
[44m[K[33m   row   6: this is some text[m
[44m[K[33m*[m
[44m[K[33m   row   7: this is some text[m
[44m[K[33m   row   8: this is some text[m
[44m[K[33m*[m
[44m[K[33m   row   9: this is some text[m
[44m[K[33m   row  10: this is some text[m
[44m[K[33m*[m
[44m[K[33m   row  11: this is some text[m
[44m[K[33m   row  12: this is some text[m
[44m[K[33m*[m
[44m[K[33m   row  13: this is some text[m
[44m[K[33m   row  14: this is some text[m
[44m[K[33m*[m
[44m[K[33m   row  15: this is some text[m
[44m[K[33m   row  16: this is some text[m
[44m[K[33m*[m
[44m[K[33m   row  17: this is some text[m
[44m[K[33m   row  18: this is some text[m
[44m[K[33m   row  19: this is some text[m
[44m[K[33m   row  20: this is some text[m
[44m[K[33m   row  21: this is some text[m
[44m[K[33m   row  22: this is some text[m
[44m[K[33m   row  23: this is some text[m
[44m[K[33m   row  24: this is some text[m
