.TH QTDOMTERM 1
.SH NAME
qtdomterm \- a terminal emulator based on Qt and web techologies
.SH SYNOPSIS
.B qtdomterm
.I "[options]"
.I [command argument ...]

.SH "DESCRIPTION"
The qtdomterm program implements a terminal emulator based on
web technologies.  This means the displayed text is structured
like a web page, and can include image, links, and annotations.
The style can be changed with CSS style sheets.

.SH SEE ALSO
.BR domterm (1)
- an alias for either ldomterm or qtdomterm
.BR ldomterm(1)
.PP
.BR "http://domterm.org/"
- the DomTerm home page
